In [22]:
import requests
import pandas as pd
from time import sleep

# url = 'https://www.ura.gov.sg/realEstateIIWeb/transaction/submitSearch.action;jsessionid=ZNK2EiZwv5-eblsBdX9eKN-hR_XHY7HUSIi0KvTGz8Q8lCxNfwVG!-1985331744!-1709263149'

post_url = "https://www.ura.gov.sg/realEstateIIWeb/transaction/submitSearch.action"
get_url = "https://www.ura.gov.sg/realEstateIIWeb/transaction/search.action"
max_postal_district_list = 28

form_data = {
    'submissionType': 'pd',
    'selectedFromPeriodProjectName': 'MAR 2017',
    'selectedToPeriodProjectName': 'FEB 2020',
    '__multiselect_selectedProjects1': None, 
    'selectedFromPeriodPostalDistrict': 'MAR 2017',
    'selectedToPeriodPostalDistrict': 'FEB 2020',
    'propertyType': 'ac',
    'postalDistrictList': '28',
    'selectedPostalDistricts1': '01',
    '__multiselect_selectedPostalDistricts1': None 
}

session = requests.Session()
session.get(get_url)

# Sleep is necessary here to somehow allow their backend to persist the cookie first
sleep(3)

cookies = requests.utils.dict_from_cookiejar(session.cookies)
post_url = post_url + ';jsessionid=' + cookies['JSESSIONID']

for i in range(1, max_postal_district_list + 1):
    print(f"scraping for district {i}...")
    
    postal_district = f'0{i}' if i < 10 else str(i)
    form_data['selectedPostalDistricts1'] = postal_district
    resp = session.post(post_url, form_data)
    print(resp.text)
    df = pd.read_html(resp.text)[0]
    break
#     df.to_csv(f'data/ac_{postal_district}.csv', index=False)

scraping for district 1...













<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="description" content="">
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; minimum-scale=1.0; user-scalable=no; target-densityDpi=device-dpi">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Private Residential Property Transactions</title>

<!-- Common CSS files -->
<link rel="stylesheet" href="/wr5/docroot/css/normalize.css">
<link rel="stylesheet" href="/wr5/docroot/css/bootstrap-css/bootstrap.min.css">
<link rel="stylesheet" href="/wr5/docroot/css/bootstrap-css/bootstrap-theme.min.css">
<link rel="stylesheet" href="/wr5/docroot/css/vendor/jquery-ui-1.10.1.css">
<link rel="stylesheet" href="/wr5/docroot/css/vendor/latoja.datepicker.css">
<link rel="stylesheet" href="/wr5/docroot/css/her-style.css">
<link rel="stylesheet" href="/wr5/docroot/css/aja-style.css">
<link rel="stylesheet" href="/wr5/docroot/css/clean.css">
<link rel="stylesheet" href="/wr5/docroot/css/table.css">
<link rel="stylesheet" href="/wr5/docroot/css/main.css">
<script src="/wr5/docroot/js/vendor/jquery-1.11.3.min.js"></script>
<script src="/wr5/docroot/js/vendor/jquery-ui-1.10.1.min.js"></script>
<script src="/wr5/docroot/js/vendor/jquery.floatThead.min.js"></script>
<script src="/realEstateIIWeb/resources/scripts/common.js"></script>
<script src="/realEstateIIWeb/resources/scripts/menuswapper.js"></script>
</head>
<body>
	<div class="pageholder pageholderFull">
		<!--Top Header Start-->
		<header class="containerFullWidth">
			<div class="col-sm-6 uraLogoHolder padding0  text-left">
				<a href="#">
					<img src="/wr5/docroot/img/uralogo.png" alt="URA - Urban Redevelopment Authority">
					<br />
					<span class="uraLogoTagline">To make singapore a great city to live, work and play in</span>
				</a>
			</div>
			<div class="col-sm-6 padding0 uraLogoHolder singaporeLogo text-right hidden-xs">
				<a href="#">
					<img src="/wr5/docroot/img/sglogo_tagline.png" alt="Singapore government">
				</a>
			</div>
		</header>
		<!--Top Header Closed-->







<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<!-- MenuBar starts from here   -->
<div class="container-fluid titleHolder">
	<div class="containerFullWidth titleContainer">
		<h1 class="pageTitle">
			Private Residential Property Transactions
		</h1>
		<div class="menuHolder">
			<a role="button" data-toggle="collapse" href="#menuList" aria-expanded="false" aria-controls="menuList" class="menuBtn hideOnMobile showOnDesktop">
				<img src="/wr5/docroot/img/icons/menu-icon.png" alt="">
				<!-- <span class="glyphicon glyphicon-th-list"></span> -->
			</a>
			<a role="button" data-toggle="collapse" href="#menuList1" aria-expanded="false" aria-controls="menuList" class="menuBtn hideOnDesktop showOnMobile">
				<img src="/wr5/docroot/img/icons/menu-icon.png" alt="">
				<!-- <span class="glyphicon glyphicon-th-list"></span> -->
			</a>
		</div>
		<ul class="menuList collapse hideOnMobile" id="menuList">

			<li>
				<a href="/eservices_docs/lad/pmi/Glossary.html" class="sublinks" target="_blank">GLOSSARY</a>
			</li>

			<li>
				<a href="/eservices_docs/lad/pmi/TnC.html" class="sublinks" target="_blank">TERMS AND CONDITIONS</a>
			</li>

			<li>
				<a href="http://www.ifaq.gov.sg/URA/apps/Fcd_faqmain.aspx?TOPIC=8884&HIDETOPICS=1" class="sublinks" target="_blank">FAQs</a>
			</li>

		</ul>

	</div>
	<ul class="menuList collapse hideOnDesktop" id="menuList1">

		<li>
			<a href="/eservices_docs/lad/pmi/Glossary.html" class="sublinks" target="_blank">GLOSSARY</a>
		</li>

		<li>
			<a href="/eservices_docs/lad/pmi/TnC.html" class="sublinks" target="_blank">TERMS AND CONDITIONS</a>
		</li>

		<li>
			<a href="http://www.ifaq.gov.sg/URA/apps/Fcd_faqmain.aspx?TOPIC=8884&HIDETOPICS=1" class="sublinks" target="_blank">FAQs</a>
		</li>

	</ul>
</div>
<!-- MenuBar finishes from here  -->
<div class="containerFullWidth">



		<div class="stepsHolder clear clearfix mgTop1">
			<span class="stepHeading">Step</span>
			<ul class="stepsContainer">



						<li class="">
							<a href="#">
								<span>1</span>
							</a>
						</li>
						<li class="stepActive noMargin">
							<a href="#">
								<span>2</span>
							</a>
						</li>


				<li class="stepsBackLine"></li>
			</ul>
		</div>



	<!-- Tabs Holder starts from here -->

	<!-- selection Dropdown starts from here -->

	<div class="mgTop1 mgBtm1 clear clearfix">
		<div class="form-group">
			<label for="selection" class="col-sm-3 control-label" style="margin-top: 8px;">Other Related e-Services:</label>
			<div class="col-sm-9">

				<select onchange="javascript:changeModule(this.value)" id="selectbasic" name="selectbasic" class="form-control">


							<option value="transaction" selected>Private Residential Property Transactions</option>






							<option value="rental">Median Rentals of Private Non-Landed Residential Properties by Name</option>





							<option value="resiRental">Rental Contracts of Private Residential Properties</option>





							<option value="price">Prices of Private Residential Units Sold By Developers</option>





							<option value="supply">Private Residential Projects in the Pipeline</option>


				</select>
			</div>
		</div>
	</div>

	<!-- selection Dropdown Ends here -->


<script language="javascript">
	function printResultsLink(url) {
		window.location.href = url;
	}

	function setSortBy(sortby) {
		document.getElementById("sortby").value = sortby;
		document.SubmitSortForm.method = "post";
		document.SubmitSortForm.submit();
	}

	function popUp(URL) {
		newWin = window
				.open(
						'',
						'',
						'status=yes,menubar=yes,scrollbars=yes,toolbar=yes,location=yes,directories=yes,resizable=yes,top=0,left=0');
		newWin.moveTo(0, 0);
		newWin.resizeTo(screen.availWidth, screen.availHeight);
		newWin.location.href = URL;
	}

	function changeDisplayUnit() {
		document.SubmitSortForm.method = "post";
		document.SubmitSortForm.action = "changeDisplayUnit.action";
		document.SubmitSortForm.submit();
	}
</script>
<style>
th:hover {
	cursor: pointer;
	cursor: hand;
}
</style>




<form id="SubmitSortForm" name="SubmitSortForm" action="/realEstateIIWeb/transaction/submitSort.action" method="post">
	<input type="hidden" name="sortBy" value="" id="sortby"/>
	<!-- info panel starts from here -->
	<div class="panel panel-default infoPanelHolder panelHolder">
		<div class="panel-heading">
			<h3 class="panel-title">
				Information
				<span class="glyphicon floatright expClpIcon glyphicon-plus-sign"></span>
			</h3>
		</div>
		<div class="panel-body">
			<div class="initialPanelContent">
				<ol>
					<li>For landed housing, the Land/Floor Area refers to the land area.</li>
				</ol>
			</div>

			<div class="mainPanelContent">
				<ol>
					<li>For landed housing, the Land/Floor Area refers to the land area.</li>
					<li>For non-landed housing, the floor area of the unit is shown.</li>
					<li>Transactions that were done more than 36 months ago are not shown. Find out more from the FAQs.</li>
					<li>
						Projects in this database are grouped by Core Central Region (CCR), Rest of Central Region (RCR) and Outside Central Region (OCR).
						<a href="http://spring.ura.gov.sg/lad/ore/login/map_ccr.pdf" target="blank">Click here</a>
						to view the map of the Central Region and areas in Core Central Region.
					</li>
					<li>Price ($) refers to the purchase price stated in the Option and S&P agreement and would have already deducted upfront direct discounts (e.g. X% early bird discount), if any.</li>
					<li>Nett Price ($) refers to the purchase price of a unit after deducting both upfront direct discounts and amount or value of any benefit or benefits given or agreed to be given of units sold.</li>

				</ol>
			</div>
			<div class="text-right">
				<a href="#" class="initialPanelContent readLinkPanel">Read more</a>
				<a href="#" class="mainPanelContent readLinkPanel">Read less</a>
			</div>
		</div>
	</div>
	<!-- info panel finishes here -->

	<div class="row formRow btnRadioContainer" data-toggle="buttons">
		<div class="col-sm-12">
			<label>Search Result: </label>
			687
			Record(s) Retrieved
		</div>
		<div class="col-sm-4">

			<input type="button" class="btn btn-default btn-block mgbottom07" value="Print PDF" onclick="link('/realEstateIIWeb/transaction/submitPrintResults.action');">
		</div>
		<div class="col-sm-4">

			<input type="button" class="btn btn-default btn-block mgbottom07" value="Download into CSV" onclick="link('/realEstateIIWeb/transaction/submitExcelResults.action');">
		</div>
		<div class="col-sm-4">

			<input type="button" class="btn btn-default btn-block mgbottom07" value="Modify Search Criteria" onclick="link('/realEstateIIWeb/transaction/search.action');">
		</div>
	</div>
	<div class="row formRow">
		<div class="col-xs-12 col-sm-4 pull-right">
			<select id="timeSelect" class="form-control" onchange="changeDisplayUnit();">

					<option>Display in Square Metre</option>
					<option selected="selected">Display in Square Feet</option>


			</select>
		</div>
	</div>
	<div class="clearfix pmiTableForOnePage">
		<table class="table table-responsive table-striped table-bordered responsiveTable transposeTable" >

			<thead>
				<tr>
					<th style="width: 115.2px;" onclick="javascript:setSortBy('PROJECT_NAME');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">Project Name</span>
					</th>
					<th style="width: 117.6px;" onclick="javascript:setSortBy('STREET_NAME');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">Street Name</span>
					</th>
					<th style="width: 65.6px;" onclick="javascript:setSortBy('PROPERTY_TYPE');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">Type</span>
					</th>
					<th style="width: 66.4px;" onclick="javascript:setSortBy('POSTAL_DISTRICT');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">Postal District</span>
					</th>
					<th style="width: 66.4px;" onclick="javascript:setSortBy('MARKET_SEGMENT');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">Market Segment</span>
					</th>
					<th style="width: 55.2px;" onclick="javascript:setSortBy('TENURE');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">Tenure</span>
					</th>
					<th style="width: 60px;" onclick="javascript:setSortBy('SALE_TYPE');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">Type of Sale</span>
					</th>
					<th style="width: 68.8px;" onclick="javascript:setSortBy('COVER');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">
							No. of
							<br>
							Units
						</span>
					</th>
					<th style="width: 56px;" onclick="javascript:setSortBy('PRICE');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">
							Price
							<br>
							($)
						</span>
					</th>
					<!--  Govind -->
					<th style="width: 84.8px;" onclick="javascript:setSortBy('NETT_PRICE');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">
							Nett Price
							<br>
							($)
						</span>
					</th>
					<th style="width: 88px;" onclick="javascript:setSortBy('FLOOR_LAND_AREA_SQF');">




									<span class="glyphicon glyphicon-triangle-bottom"></span>


							<span class="thHeading">
								Area (Sqft)&#185;
							</span>



					</th>
					<th onclick="javascript:setSortBy('LOT_TYPE');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">
							Type of Area&#178;
						</span>

					</th>
					<th onclick="javascript:setSortBy('FLOOR_LEVEL');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">Floor Level</span>
					</th>
					<th onclick="javascript:setSortBy('PRICE_PSF');">




									<span class="glyphicon glyphicon-triangle-bottom"></span>


							<span class="thHeading">
								Unit Price ($psf)&#179;
							</span>


					</th>
					<th onclick="javascript:setSortBy('CONTRACT_DATE');">



								<span class="glyphicon glyphicon-triangle-bottom"></span>


						<span class="thHeading">
							Date of Sale&#8308;
						</span>
					</th>
				</tr>
			</thead>
			<tbody>

					<tr>
						<td data-th="Project Name">
							MARINA ONE RESIDENCES
						</td>
						<td data-th="Street Name">
							MARINA WAY
						</td>
						<td data-th="Type">
							Apartment
						</td>
						<td data-th="Postal District">
							01
						</td>
						<td data-th="Market Segment">
							CCR
						</td>
						<td data-th="Tenure">
							99 yrs lease commencing from 2011
						</td>
						<td data-th="Type of Sale">
							Resale
						</td>
						<td data-th="No. of Units">
							1
						</td>
						<td data-th="Price($)">
							2,546,716
						</td>
						<!-- Govind  -->
						<td data-th="Nett Price($)">
							-
						</td>

							<td data-th="Area (Sqft)&#185;">
								1,173
							</td>


						<td data-th="Type of Area&#178;">
							Strata
						</td>
						<td data-th="Floor Level">
							11 to 15
						</td>

							<td data-th="Unit Price ($psf)&#179;">
								2,171
							</td>


						<td data-th="Date of Sale&#8308;">
							Feb-20
						</td>
					</tr>

					<tr>
						<td data-th="Project Name">
							THE SAIL @ MARINA BAY
						</td>
						<td data-th="Street Name">
							MARINA BOULEVARD
						</td>
						<td data-th="Type">
							Apartment
						</td>
						<td data-th="Postal District">
							01
						</td>
						<td data-th="Market Segment">
							CCR
						</td>
						<td data-th="Tenure">
							99 yrs lease commencing from 2002
						</td>
						<td data-th="Type of Sale">
							Resale
						</td>
						<td data-th="No. of Units">
							1
						</td>
						<td data-th="Price($)">
							1,200,000
						</td>
						<!-- Govind  -->
						<td data-th="Nett Price($)">
							-
						</td>

							<td data-th="Area (Sqft)&#185;">
								667
							</td>


						<td data-th="Type of Area&#178;">
							Strata
						</td>
						<td data-th="Floor Level">
							56 to 60
						</td>

							<td data-th="Unit Price ($psf)&#179;">
								1,798
							</td>


						<td data-th="Date of Sale&#8308;">
							Feb-20
						</td>
					</tr>

					<tr>
						<td data-th="Project Name">
							ONE SHENTON
						</td>
						<td data-th="Street Name">
							SHENTON WAY
						</td>
						<td data-th="Type">
							Apartment
						</td>
						<td data-th="Postal District">
							01
						</td>
						<td data-th="Market Segment">
							CCR
						</td>
						<td data-th="Tenure">
							99 yrs lease commencing from 2005
						</td>
						<td data-th="Type of Sale">
							Resale
						</td>
						<td data-th="No. of Units">
							1
						</td>
						<td data-th="Price($)">
							1,080,000
						</td>
						<!-- Govind  -->
						<td data-th="Nett Price($)">
							-
						</td>

							<td data-th="Area (Sqft)&#185;">
								581
							</td>


						<td data-th="Type of Area&#178;">
							Strata
						</td>
						<td data-th="Floor Level">
							31 to 35
						</td>

							<td data-th="Unit Price ($psf)&#179;">
								1,858
							</td>


						<td data-th="Date of Sale&#8308;">
							Feb-20
						</td>
					</tr>

					<tr>
						<td data-th="Project Name">
							MARINA ONE RESIDENCES
						</td>
						<td data-th="Street Name">
							MARINA WAY
						</td>
						<td data-th="Type">
							Apartment
						</td>
						<td data-th="Postal District">
							01
						</td>
						<td data-th="Market Segment">
							CCR
						</td>
						<td data-th="Tenure">
							99 yrs lease commencing from 2011
						</td>
						<td data-th="Type of Sale">
							Resale
						</td>
						<td data-th="No. of Units">
							1
						</td>
						<td data-th="Price($)">
							1,768,540
						</td>
						<!-- Govind  -->
						<td data-th="Nett Price($)">
							-
						</td>

							<td data-th="Area (Sqft)&#185;">
								753
							</td>


						<td data-th="Type of Area&#178;">
							Strata
						</td>
						<td data-th="Floor Level">
							21 to 25
						</td>

							<td data-th="Unit Price ($psf)&#179;">
								2,347
							</td>


						<td data-th="Date of Sale&#8308;">
							Feb-20
						</td>
					</tr>

					<tr>
						<td data-th="Project Name">
							MARINA ONE RESIDENCES
						</td>
						<td data-th="Street Name">
							MARINA WAY
						</td>
						<td data-th="Type">
							Apartment
						</td>
						<td data-th="Postal District">
							01
						</td>
						<td data-th="Market Segment">
							CCR
						</td>
						<td data-th="Tenure">
							99 yrs lease commencing from 2011
						</td>
						<td data-th="Type of Sale">
							Resale
						</td>
						<td data-th="No. of Units">
							1
						</td>
						<td data-th="Price($)">
							2,700,364
						</td>
						<!-- Govind  -->
						<td data-th="Nett Price($)">
							-
						</td>

							<td data-th="Area (Sqft)&#185;">
								1,141
							</td>


						<td data-th="Type of Area&#178;">
							Strata
						</td>
						<td data-th="Floor Level">
							21 to 25
						</td>

							<td data-th="Unit Price ($psf)&#179;">
								2,367
							</td>


						<td data-th="Date of Sale&#8308;">
							Feb-20
						</td>
					</tr>

					<tr>
						<td data-th="Project Name">
							MARINA ONE RESIDENCES
						</td>
						<td data-th="Street Name">
							MARINA WAY
						</td>
						<td data-th="Type">
							Apartment
						</td>
						<td data-th="Postal District">
							01
						</td>
						<td data-th="Market Segment">
							CCR
						</td>
						<td data-th="Tenure">
							99 yrs lease commencing from 2011
						</td>
						<td data-th="Type of Sale">
							Resale
						</td>
						<td data-th="No. of Units">
							1
						</td>
						<td data-th="Price($)">
							1,676,684
						</td>
						<!-- Govind  -->
						<td data-th="Nett Price($)">
							-
						</td>

							<td data-th="Area (Sqft)&#185;">
								732
							</td>


						<td data-th="Type of Area&#178;">
							Strata
						</td>
						<td data-th="Floor Level">
							21 to 25
						</td>

							<td data-th="Unit Price ($psf)&#179;">
								2,291
							</td>


						<td data-th="Date of Sale&#8308;">
							Feb-20
						</td>
					</tr>

					<tr>
						<td data-th="Project Name">
							MARINA ONE RESIDENCES
						</td>
						<td data-th="Street Name">
							MARINA WAY
						</td>
						<td data-th="Type">
							Apartment
						</td>
						<td data-th="Postal District">
							01
						</td>
						<td data-th="Market Segment">
							CCR
						</td>
						<td data-th="Tenure">
							99 yrs lease commencing from 2011
						</td>
						<td data-th="Type of Sale">
							Resale
						</td>
						<td data-th="No. of Units">
							1
						</td>
						<td data-th="Price($)">
							2,379,000
						</td>
						<!-- Govind  -->
						<td data-th="Nett Price($)">
							-
						</td>

							<td data-th="Area (Sqft)&#185;">
								1,033
							</td>


						<td data-th="Type of Area&#178;">
							Strata
						</td>
						<td data-th="Floor Level">
							21 to 25
						</td>

							<td data-th="Unit Price ($psf)&#179;">
								2,302
							</td>


						<td data-th="Date of Sale&#8308;">
							Feb-20
						</td>
					</tr>

					<tr>
						<td data-th="Project Name">
							MARINA ONE RESIDENCES
						</td>
						<td data-th="Street Name">
							MARINA WAY
						</td>
						<td data-th="Type">
							Apartment

In [20]:
url

'https://www.ura.gov.sg/realEstateIIWeb/transaction/submitSearch.action;jsessionid=9BK2F7PK9sStopdvweF_ZLqG3ctzVZVOZZy0sKBzXCBoTB_xSyCS!-1985331744!-1709263149'

In [5]:
session = requests.Session()
r = session.get(get_url)

requests.utils.dict_from_cookiejar(session.cookies)

{'TS0117b822': '01e0d9e46e5fcce2228b8899635d94f2b40a2ea10ebc929720eefa317277ec21fce533c49c917dd5efbd97bc259f49f215c76081835a5d4ce2612fd75f3107432dee2fe6601551609c5a0e265d8756a6db8e5ed5c9',
 'BIGipServerIAPP-HTTPS_A83-WWW.URA.GOV.SG_V4.app~IAPP-HTTPS_A83-WWW.URA.GOV.SG_V4_pool': '952674496.20480.0000',
 'JSESSIONID': 'ZNK2EiZwv5-eblsBdX9eKN-hR_XHY7HUSIi0KvTGz8Q8lCxNfwVG!-1985331744!-1709263149',
 '_nxqsession_jsessionid': 'i8qoT9xCy494zvFBW+1sFXvbUgIRHVR6mQ04v2BRaKrGfaV9Moy2JaIO/fqPoZ2GrcG0SQMGkDUa1vDsPE+588E2eQLXIYi1DSZT8A=='}

In [6]:
jsessionid

'3Wq2EZz_P82ST30UD3GyogI6o87U4RcKJURm0Iw1utnugSvnMyWv!-1709263149!-1985331744'

In [13]:
import pandas as pd
df = pd.read_html(resp.text)

In [14]:
df[0].columns

Index(['Project Name', 'Street Name', 'Type', 'Postal District',
       'Market Segment', 'Tenure', 'Type of Sale', 'No. of  Units',
       'Price  ($)', 'Nett Price  ($)', 'Area (Sqft)¹', 'Type of Area²',
       'Floor Level', 'Unit Price ($psf)³', 'Date of Sale⁴'],
      dtype='object')

In [15]:
df[0]

,Project Name,Street Name,Type,Postal District,Market Segment,Tenure,Type of Sale,No. of Units,Price ($),Nett Price ($),Area (Sqft)¹,Type of Area²,Floor Level,Unit Price ($psf)³,Date of Sale⁴
0,SPOTTISWOODE RESIDENCES,SPOTTISWOODE PARK ROAD,Condominium,2,RCR,Freehold,Resale,1,1145000,-,603,Strata,11 to 15,1900,Feb-20
1,SKY EVERTON,EVERTON ROAD,Apartment,2,RCR,Freehold,New Sale,1,1566000,-,624,Strata,06 to 10,2508,Feb-20
2,76 SHENTON,SHENTON WAY,Apartment,2,CCR,99 yrs lease commencing from 2007,Resale,1,1660000,-,980,Strata,11 to 15,1695,Feb-20
3,THE BEACON,CANTONMENT ROAD,Apartment,2,RCR,99 yrs lease commencing from 2004,Resale,1,1000000,-,807,Strata,11 to 15,1239,Feb-20
4,SKY EVERTON,EVERTON ROAD,Apartment,2,RCR,Freehold,New Sale,1,2518000,-,958,Strata,21 to 25,2628,Jan-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798,ICON,GOPENG STREET,Apartment,2,CCR,99 yrs lease commencing from 2002,Resale,1,995000,-,581,Strata,06 to 10,1712,Mar-17
799,ICON,GOPENG STREET,Apartment,2,CCR,99 yrs lease commencing from 2002,Resale,1,1428000,-,904,Strata,16 to 20,1579,Mar-17
800,SPOTTISWOODE 18,SPOTTISWOODE PARK ROAD,Apartment,2,RCR,Freehold,Resale,1,1250000,-,635,Strata,06 to 10,1968,Mar-17
801,ONZE @ TANJONG PAGAR,KEE SENG STREET,Apartment,2,RCR,Freehold,New Sale,1,1283406,-,506,Strata,06 to 10,2537,Mar-17
802,SKYSUITES@ANSON,ENGGOR STREET,Apartment,2,CCR,99 yrs lease commencing from 2008,Resale,1,2680000,-,1012,Strata,61 to 65,2649,Mar-17

In [11]:
df[0].to_csv('data/ac_01.csv', index=False)