In [ ]:
from datetime import datetime, timedelta
import calendar
import requests
import pandas as pd
from time import sleep

In [105]:
df = pd.read_csv('data/apartments_condos/total.csv')
# filtered_df = df[df['']]
df.sort_values(['date_of_sale', 'unit_price_psf', 'price'], ascending=[False, True, True])

,project_name,street_name,type,postal_district,market_segment,tenure,type_of_sale,num_units,price,nett_price,area_sqft,type_of_area,floor_level,unit_price_psf,date_of_sale
50252,REGENT HEIGHTS,BUKIT BATOK EAST AVENUE 5,Condominium,23,OCR,99 yrs lease commencing from 1995,Resale,1,795000,-,1023,Strata,11 to 15,777,2020-03-31
50253,MAYSPRINGS,PETIR ROAD,Apartment,23,OCR,99 yrs lease commencing from 1994,Resale,1,1250000,-,1550,Strata,21 to 25,806,2020-03-31
50254,CASHEW PARK CONDOMINIUM,CASHEW ROAD,Condominium,23,OCR,999 yrs lease commencing from 1882,Resale,1,1900000,-,1819,Strata,06 to 10,1044,2020-03-31
32713,CHANGI GREEN,UPPER CHANGI ROAD EAST,Condominium,16,OCR,Freehold,Resale,1,945000,-,872,Strata,01 to 05,1084,2020-03-31
47654,SOUTHAVEN II,HINDHEDE WALK,Condominium,21,OCR,999 yrs lease commencing from 1877,Resale,1,1580000,-,1442,Strata,01 to 05,1095,2020-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15431,OUE TWIN PEAKS,LEONIE HILL ROAD,Condominium,9,CCR,99 yrs lease commencing from 2010,Resale,1,4865000,-,1604,Strata,26 to 30,3033,2017-03-31
15445,HILLTOPS,CAIRNHILL CIRCLE,Condominium,9,CCR,Freehold,Resale,1,3977000,-,1249,Strata,16 to 20,3185,2017-03-31
15440,OUE TWIN PEAKS,LEONIE HILL ROAD,Condominium,9,CCR,99 yrs lease commencing from 2010,Resale,1,1855800,-,570,Strata,21 to 25,3253,2017-03-31
15413,THE ORCHARD RESIDENCES,ORCHARD BOULEVARD,Apartment,9,CCR,99 yrs lease commencing from 2006,Resale,1,7400000,-,2174,Strata,46 to 50,3403,2017-03-31
18920,LE NOUVEL ARDMORE,ARDMORE PARK,Condominium,10,CCR,Freehold,Resale,1,15174945,-,3789,Strata,21 to 25,4005,2017-03-31