In [1]:
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv('data/transaction_summary.csv')
df['property_type'].unique()

array(['Non-Landed', 'Strata-Landed', 'Landed', 'Exec Condo',
       'Strata-Landed / Non-Landed', 'Landed / Non-Landed'], dtype=object)

In [3]:
df_non_landed = df[df['property_type'] == 'Non-Landed']
df_non_landed.sort_values(['reference_period'], ascending=False)
# df_non_landed.groupby([''])

,project_name,street_name,developer,property_type,locality,total_num_units_in_project,cumulative_units_launched_to_date,cumulative_units_sold_to_date,total_num_unsold_units,cumulative_units_launched_unsold,units_launched_month,units_sold_month,median_price_psf,lowest_price_psf,highest_price_psf,reference_period
52812,WILSHIRE RESIDENCES,FARRER ROAD,TE2KS-RH Pte Ltd,Non-Landed,CCR,85,20,10,75,10,0,0,-,-,-,2020-08-31
52717,LATTICE ONE,SERAYA CRESCENT,Amcorp Development Pte Ltd,Non-Landed,OCR,48,48,31,17,17,0,1,"1,612",1612,1612,2020-08-31
52701,GRANDEUR PARK RESIDENCES,BEDOK SOUTH AVENUE 3,CEL-Changi Pte Ltd,Non-Landed,OCR,720,720,712,8,8,0,2,"1,609",1588,1629,2020-08-31
52702,GRANGE 1866,GRANGE ROAD,Grange 1866 Pte Ltd,Non-Landed,CCR,60,0,0,60,0,0,0,-,-,-,2020-08-31
52703,HAUS ON HANDY,HANDY ROAD,CDL Regulus Pte Ltd,Non-Landed,CCR,188,40,35,153,5,0,1,"2,755",2755,2755,2020-08-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,SUNSHINE GRANDEUR,LORONG K TELOK KURAU,Fragrance Land Pte Ltd,Non-Landed,OCR,18,18,18,0,0,0,0,-,-,-,2007-06-30
219,SUN CREST,ST. MICHAEL'S ROAD,Came Enterprises Pte Ltd,Non-Landed,RCR,83,0,0,83,0,0,0,-,-,-,2007-06-30
217,SUITES @ SURREY,SURREY ROAD,Springlife Land Pte Ltd,Non-Landed,CCR,20,20,20,0,0,0,0,-,-,-,2007-06-30
216,SUITES @ CAIRNHILL,ANTHONY ROAD,Hoi Hup Realty Pte Ltd,Non-Landed,CCR,48,48,48,0,0,0,0,-,-,-,2007-06-30
0,38 AMBER,AMBER ROAD,Ho Brothers Investment Pte Ltd,Non-Landed,RCR,30,0,0,30,0,0,0,-,-,-,2007-06-30

In [5]:
condo_name = 'MIDWOOD'

df[df['project_name'].str.contains(condo_name)].sort_values('reference_period', ascending=False)

,project_name,street_name,developer,property_type,locality,total_num_units_in_project,cumulative_units_launched_to_date,cumulative_units_sold_to_date,total_num_unsold_units,cumulative_units_launched_unsold,units_launched_month,units_sold_month,median_price_psf,lowest_price_psf,highest_price_psf,reference_period
52730,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,24,540,76,0,0,-,-,-,2020-08-31
52579,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,24,540,76,0,0,-,-,-,2020-07-31
52429,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,24,540,76,0,0,-,-,-,2020-06-30
52277,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,24,540,76,0,0,-,-,-,2020-05-31
52124,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,25,539,75,0,0,-,-,-,2020-04-30
51969,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,28,536,72,0,1,"1,626",1626,1626,2020-03-31
51816,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,27,537,73,0,4,"1,606",1563,1729,2020-02-29
51662,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,25,539,75,0,4,"1,641",1535,1722,2020-01-31
51506,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,21,543,79,0,1,"1,652",1652,1652,2019-12-31
51356,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,24,540,76,0,10,"1,628",1551,1751,2019-11-30
51204,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,100,24,540,76,100,24,"1,640",1555,1748,2019-10-31
51058,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,0,0,564,0,0,0,-,-,-,2019-09-30
50914,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,0,0,564,0,0,0,-,-,-,2019-08-31
50771,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,0,0,564,0,0,0,-,-,-,2019-07-31
50630,MIDWOOD,HILLVIEW RISE,Hillview Rise Development Pte Ltd,Non-Landed,OCR,564,0,0,564,0,0,0,-,-,-,2019-06-30

In [5]:
df[df['project_name'].str.contains('PARC CLEMATIS')].sort_values('reference_period', ascending=False)

,project_name,street_name,developer,property_type,locality,total_num_units_in_project,cumulative_units_launched_to_date,cumulative_units_sold_to_date,total_num_unsold_units,cumulative_units_launched_unsold,units_launched_month,units_sold_month,median_price_psf,lowest_price_psf,highest_price_psf,reference_period
52595,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,1000,840,628,160,0,87,"1,649",1044,1739,2020-07-31
52444,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,1000,758,710,242,0,90,"1,637",1052,1710,2020-06-30
52292,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,1000,673,795,327,335,55,"1,599",1047,1686,2020-05-31
52140,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,665,623,845,42,0,9,"1,609",1504,1647,2020-04-30
51986,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,665,615,853,50,0,26,"1,592",1406,1695,2020-03-31
51833,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,665,592,876,73,0,31,"1,579",1368,1674,2020-02-29
51680,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,665,564,904,101,0,39,"1,610",1025,1712,2020-01-31
51524,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,665,528,940,137,0,40,"1,638",1333,1713,2019-12-31
51370,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,665,492,976,173,0,36,"1,600",1520,1715,2019-11-30
51218,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,665,461,1007,204,0,32,"1,606",1041,1697,2019-10-31
51071,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,665,434,1034,231,225,119,"1,620",1014,1754,2019-09-30
50926,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,440,316,1152,124,440,316,"1,615",1025,1711,2019-08-31
50783,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,0,0,1468,0,0,0,-,-,-,2019-07-31
50642,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,0,0,1468,0,0,0,-,-,-,2019-06-30

In [48]:
df[df['reference_period'] == '2020-02-29'].sort_values('units_sold_month', ascending=False).head(10)

,project_name,street_name,developer,property_type,locality,total_num_units_in_project,cumulative_units_launched_to_date,cumulative_units_sold_to_date,total_num_unsold_units,cumulative_units_launched_unsold,units_launched_month,units_sold_month,median_price_psf,lowest_price_psf,highest_price_psf,reference_period
51880,THE M,MIDDLE ROAD,Wingcharm Investment Pte Ltd,Non-Landed,CCR,522,522,380,142,142,522,380,"2,439",2127,2937,2020-02-29
51830,PARC CANBERRA,CANBERRA WALK,Hoi Hup Sunway Canberra Pte Ltd,Exec Condo,OCR,496,496,324,172,172,496,324,"1,111",970,1199,2020-02-29
51887,TREASURE AT TAMPINES,TAMPINES LANE,Sim Lian (Treasure) Pte Ltd,Non-Landed,OCR,2203,1100,1012,1191,88,150,97,"1,379",1216,1517,2020-02-29
51832,PARC ESTA,SIMS AVENUE,MCL Land (Everbright) Pte Ltd,Non-Landed,RCR,1399,1150,1105,294,45,75,53,"1,686",1602,1907,2020-02-29
51792,JADESCAPE,SHUNFU ROAD,Qingjian Realty (Marymount) Pte Ltd,Non-Landed,RCR,1206,800,669,537,131,0,46,"1,707",1506,1837,2020-02-29
51829,PARC BOTANNIA,FERNVALE STREET,Fernvale Green Pte Ltd,Non-Landed,OCR,735,735,722,13,13,0,40,"1,376",1213,1461,2020-02-29
51831,PARC CLEMATIS,JALAN LEMPENG,Sing-Haiyi Gold Pte Ltd,Non-Landed,OCR,1468,665,592,876,73,0,31,"1,579",1368,1674,2020-02-29
51895,VIEW AT KISMIS,LORONG KISMIS,Roxy-TE2 Development Pte Ltd,Non-Landed,RCR,186,100,84,102,16,20,22,"1,696",1589,1797,2020-02-29
51873,THE GARDEN RESIDENCES,SERANGOON NORTH VIEW,Gardens Development Pte Ltd,Non-Landed,OCR,613,320,264,349,56,57,21,"1,567",1382,1654,2020-02-29
51842,PIERMONT GRAND,SUMANG WALK,Pavo Properties Pte Ltd,Exec Condo,OCR,820,820,488,332,332,0,15,"1,106",1017,1167,2020-02-29